### ISSUE TITLE
Version 0.0.7 seems not to work in a JS environment

### ISSUE THREAD

**Issue by alainkaiser** [faustomorales/retinanetjs#7]
Hi
Tried to add the package retinanetjs with the command `npm i retinanetjs` to a newly created react app (Create React App).

I noticed that the following import does not work.

`import { load } from 'retinanetjs';`

My react app loggs the following error -> Module not found: Can't resolve 'retinanetjs' in file...
Additional to that, I noticed that the node_modules folder for 'retinanetjs' is empty (only the LICENSE, package.json and readme.md file are present in the folder).

Would be great if you could fix this one!
Thanks

**Comment by faustomorales** [comment]
Yikes. Really sorry about that. This is fixed in v0.0.8. Closing for now but please comment back if the issue persists.
